CREATE TABLE IF NOT EXISTS pds_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    surname VARCHAR(500) NOT NULL,
    firstname VARCHAR(500) NOT NULL,
    middlename VARCHAR(500) NOT NULL DEFAULT '',
    dateofbirth DATE NULL,
    mobile VARCHAR(500) NOT NULL DEFAULT '',
    email VARCHAR(500) NOT NULL DEFAULT '',
    data JSON NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX records_updated (updated_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
