-- Run against a dedicated PDS database. Application connections use UTC.
CREATE TABLE IF NOT EXISTS staff_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_staff_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS login_throttles (
    throttle_key CHAR(64) NOT NULL,
    failed_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    window_started_at DATETIME(6) NOT NULL,
    locked_until DATETIME(6) NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (throttle_key),
    KEY idx_login_throttles_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pds_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    surname VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    name_extension VARCHAR(100) NULL,
    middle_name VARCHAR(100) NULL,
    birth_date DATE NOT NULL,
    birth_place VARCHAR(255) NULL,
    sex_at_birth ENUM('male', 'female') NULL,
    height_m DECIMAL(4,2) NULL,
    weight_kg DECIMAL(6,2) NULL,
    blood_type ENUM('O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-') NULL,
    umid_number VARCHAR(50) NULL,
    pagibig_number VARCHAR(50) NULL,
    philhealth_number VARCHAR(50) NULL,
    philsys_number VARCHAR(50) NULL,
    tin_number VARCHAR(50) NULL,
    agency_employee_number VARCHAR(50) NULL,
    citizenship_type ENUM('filipino', 'dual') NULL,
    dual_citizenship_details VARCHAR(255) NULL,
    residential_house VARCHAR(100) NULL,
    residential_street VARCHAR(150) NULL,
    residential_subdivision VARCHAR(150) NULL,
    residential_barangay VARCHAR(150) NULL,
    residential_city VARCHAR(150) NULL,
    residential_province VARCHAR(150) NULL,
    residential_zip VARCHAR(20) NULL,
    permanent_house VARCHAR(100) NULL,
    permanent_street VARCHAR(150) NULL,
    permanent_subdivision VARCHAR(150) NULL,
    permanent_barangay VARCHAR(150) NULL,
    permanent_city VARCHAR(150) NULL,
    permanent_province VARCHAR(150) NULL,
    permanent_zip VARCHAR(20) NULL,
    telephone VARCHAR(50) NULL,
    mobile VARCHAR(50) NULL,
    email VARCHAR(254) NULL,
    spouse_surname VARCHAR(100) NULL,
    spouse_first_name VARCHAR(100) NULL,
    spouse_name_extension VARCHAR(100) NULL,
    spouse_middle_name VARCHAR(100) NULL,
    spouse_occupation VARCHAR(150) NULL,
    spouse_employer VARCHAR(255) NULL,
    spouse_business_address VARCHAR(255) NULL,
    spouse_telephone VARCHAR(50) NULL,
    father_surname VARCHAR(100) NULL,
    father_first_name VARCHAR(100) NULL,
    father_name_extension VARCHAR(100) NULL,
    father_middle_name VARCHAR(100) NULL,
    mother_surname VARCHAR(100) NULL,
    mother_first_name VARCHAR(100) NULL,
    mother_name_extension VARCHAR(100) NULL,
    mother_middle_name VARCHAR(100) NULL,
    signatory_name VARCHAR(200) NULL,
    signature_date DATE NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    archived_at DATETIME(6) NULL,
    archived_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pds_agency_employee_number (agency_employee_number),
    KEY idx_pds_name (surname, first_name),
    KEY idx_pds_email (email),
    KEY idx_pds_archive_updated (archived_at, updated_at),
    CONSTRAINT fk_pds_created_by FOREIGN KEY (created_by) REFERENCES staff_users (id),
    CONSTRAINT fk_pds_updated_by FOREIGN KEY (updated_by) REFERENCES staff_users (id),
    CONSTRAINT fk_pds_archived_by FOREIGN KEY (archived_by) REFERENCES staff_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pds_children (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pds_id BIGINT UNSIGNED NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    birth_date DATE NULL,
    sort_order INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    KEY idx_pds_children_order (pds_id, sort_order),
    CONSTRAINT fk_children_pds FOREIGN KEY (pds_id) REFERENCES pds_records (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pds_education (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pds_id BIGINT UNSIGNED NOT NULL,
    level ENUM('elementary', 'secondary', 'vocational', 'college', 'graduate') NOT NULL,
    school_name VARCHAR(255) NULL,
    degree_course VARCHAR(255) NULL,
    attendance_from_year SMALLINT UNSIGNED NULL,
    attendance_to_year SMALLINT UNSIGNED NULL,
    highest_units_earned VARCHAR(100) NULL,
    graduation_year SMALLINT UNSIGNED NULL,
    honors VARCHAR(255) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pds_education_level (pds_id, level),
    CONSTRAINT fk_education_pds FOREIGN KEY (pds_id) REFERENCES pds_records (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    staff_user_id BIGINT UNSIGNED NULL,
    pds_id BIGINT UNSIGNED NULL,
    action ENUM('login_success', 'login_failure', 'create', 'update', 'archive', 'restore') NOT NULL,
    occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    metadata JSON NULL,
    PRIMARY KEY (id),
    KEY idx_audit_staff_time (staff_user_id, occurred_at),
    KEY idx_audit_pds_time (pds_id, occurred_at),
    CONSTRAINT fk_audit_staff FOREIGN KEY (staff_user_id) REFERENCES staff_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_pds FOREIGN KEY (pds_id) REFERENCES pds_records (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
